[[emoji]]
match = "(?i:流量|时间|应急|过期|Bandwidth|expire)"
emoji = "🏳️‍🌈"

[[emoji]]
match = "AC"
emoji = "🇦🇨"

[[emoji]]
match = "(AR|阿根廷)"
emoji = "🇦🇷"

[[emoji]]
match = "(奥地利|维也纳)"
emoji = "🇦🇹"

[[emoji]]
match = "(AU|Australia|Sydney|澳大利亚|悉尼)"
emoji = "🇦🇺"

[[emoji]]
match = "(BE|比利时)"
emoji = "🇧🇪"

[[emoji]]
match = "(BR|Brazil|巴西|圣保罗)"
emoji = "🇧🇷"

[[emoji]]
match = "(Canada|加拿大|蒙特利尔|温哥华|楓葉|枫叶)"
emoji = "🇨🇦"

[[emoji]]
match = "(瑞士|苏黎世)"
emoji = "🇨🇭"

[[emoji]]
match = "(DE|Germany|法兰克福|德)"
emoji = "🇩🇪"

[[emoji]]
match = "丹麦"
emoji = "🇩🇰"

[[emoji]]
match = "(ES|西班牙)"
emoji = "🇪🇸"

[[emoji]]
match = "EU"
emoji = "🇪🇺"

[[emoji]]
match = "(Finland|芬兰|赫尔辛基)"
emoji = "🇫🇮"

[[emoji]]
match = "(FR|France|法国|巴黎)"
emoji = "🇫🇷"

[[emoji]]
match = "(?i:UK|England|United.*?Kingdom|英国|[^-]英|伦敦)"
emoji = "🇬🇧"

[[emoji]]
match = "(?i:HK|Hong.*?Kong|HKT|HKBN|HGC|WTT|CMI|[^-]港)"
emoji = "🇭🇰"

[[emoji]]
match = "(Indonesia|印尼|印度尼西亚|雅加达)"
emoji = "🇮🇩"

[[emoji]]
match = "(Ireland|爱尔兰|都柏林)"
emoji = "🇮🇪"

[[emoji]]
match = "(India|印度|孟买)"
emoji = "🇮🇳"

[[emoji]]
match = "(Italy|意大利|米兰)"
emoji = "🇮🇹"

[[emoji]]
match = "(尼日利亚)"
emoji = "🇳🇬"

[[emoji]]
match = "(JP|Japan|日本|[^-]日)"
emoji = "🇯🇵"

[[emoji]]
match = "(KP|朝鲜)"
emoji = "🇰🇵"

[[emoji]]
match = "(KR|Korea|KOR|首尔|韩|韓)"
emoji = "🇰🇷"

[[emoji]]
match = "(MO|Macao|澳门|CTM)"
emoji = "🇲🇴"

[[emoji]]
match = "(柬埔寨)"
emoji = "🇰🇭"

[[emoji]]
match = "(伊朗)"
emoji = "🇮🇷"

[[emoji]]
match = "(蒙古)"
emoji = "🇲🇳"

[[emoji]]
match = "(以色列)"
emoji = "🇮🇱"

[[emoji]]
match = "(尼泊尔)"
emoji = "🇳🇵"

[[emoji]]
match = "(孟加拉)"
emoji = "🇧🇩"

[[emoji]]
match = "(阿联酋)"
emoji = "🇦🇪"

[[emoji]]
match = "(阿塞拜疆)"
emoji = "🇦🇿"

[[emoji]]
match = "(格鲁吉亚)"
emoji = "🇬🇪"

[[emoji]]
match = "(巴基斯坦)"
emoji = "🇵🇰"

[[emoji]]
match = "(哈萨克斯坦)"
emoji = "🇰🇿"

[[emoji]]
match = "(吉尔吉斯斯坦)"
emoji = "🇰🇬"

[[emoji]]
match = "(马恩岛)"
emoji = "🇮🇲"

[[emoji]]
match = "(挪威)"
emoji = "🇳🇴"

[[emoji]]
match = "(冰岛)"
emoji = "🇮🇸"

[[emoji]]
match = "(捷克)"
emoji = "🇨🇿"

[[emoji]]
match = "(希腊)"
emoji = "🇬🇷"

[[emoji]]
match = "(波兰)"
emoji = "🇵🇱"

[[emoji]]
match = "(乌克兰)"
emoji = "🇺🇦"

[[emoji]]
match = "(匈牙利)"
emoji = "🇭🇺"

[[emoji]]
match = "(卢森堡)"
emoji = "🇱🇺"

[[emoji]]
match = "(立陶宛)"
emoji = "🇱🇹"

[[emoji]]
match = "(葡萄牙)"
emoji = "🇵🇹"

[[emoji]]
match = "(保加利亚)"
emoji = "🇧🇬"

[[emoji]]
match = "(克罗地亚)"
emoji = "🇭🇷"

[[emoji]]
match = "(北马其顿)"
emoji = "🇲🇰"

[[emoji]]
match = "(塞尔维亚)"
emoji = "🇷🇸"

[[emoji]]
match = "(塞浦路斯)"
emoji = "🇨🇾"

[[emoji]]
match = "(拉脱维亚)"
emoji = "🇱🇻"

[[emoji]]
match = "(摩尔多瓦)"
emoji = "🇲🇩"

[[emoji]]
match = "(斯洛伐克)"
emoji = "🇸🇰"

[[emoji]]
match = "(爱沙尼亚)"
emoji = "🇪🇪"

[[emoji]]
match = "(斯洛文尼亚)"
emoji = "🇸🇮"

[[emoji]]
match = "(波黑)"
emoji = "🇧🇦"

[[emoji]]
match = "(墨西哥)"
emoji = "🇲🇽"

[[emoji]]
match = "(巴拿马)"
emoji = "🇵🇦"

[[emoji]]
match = "(哥斯达黎加)"
emoji = "🇨🇷"

[[emoji]]
match = "(智利)"
emoji = "🇨🇱"

[[emoji]]
match = "(秘鲁)"
emoji = "🇵🇪"

[[emoji]]
match = "(乌拉圭)"
emoji = "🇺🇾"

[[emoji]]
match = "(哥伦比亚)"
emoji = "🇨🇴"

[[emoji]]
match = "(委内瑞拉)"
emoji = "🇻🇪"

[[emoji]]
match = "(埃及)"
emoji = "🇪🇬"

[[emoji]]
match = "(摩洛哥)"
emoji = "🇲🇦"

[[emoji]]
match = "(突尼斯)"
emoji = "🇹🇳"

[[emoji]]
match = "(肯尼亚)"
emoji = "🇰🇪"

[[emoji]]
match = "(约旦)"
emoji = "🇯🇴"

[[emoji]]
match = "(MY|Malaysia|马来西亚)"
emoji = "🇲🇾"

[[emoji]]
match = "(NL|Netherlands|荷兰|阿姆斯特丹)"
emoji = "🇳🇱"

[[emoji]]
match = "(PH|Philippines|菲律宾)"
emoji = "🇵🇭"

[[emoji]]
match = "(RO|罗马尼亚)"
emoji = "🇷🇴"

[[emoji]]
match = "(白俄罗斯)"
emoji = "🇧🇾"

[[emoji]]
match = "(RU|Russia|伯力|莫斯科|圣彼得堡|西伯利亚|新西伯利亚|俄罗斯|[^-]俄)"
emoji = "🇷🇺"

[[emoji]]
match = "(沙特|迪拜)"
emoji = "🇸🇦"

[[emoji]]
match = "(SE|Sweden|瑞典)"
emoji = "🇸🇪"

[[emoji]]
match = "(SG|Singapore|新加坡|狮城|[^-]新)"
emoji = "🇸🇬"

[[emoji]]
match = "(TH|Thailand|泰国|曼谷)"
emoji = "🇹🇭"

[[emoji]]
match = "(TR|Turkey|土耳其|伊斯坦布尔)"
emoji = "🇹🇷"

[[emoji]]
match = "(?i:US|America|United.*?States|美国|[^-]美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥)"
emoji = "🇺🇲"

[[emoji]]
match = "(VN|越南)"
emoji = "🇻🇳"

[[emoji]]
match = "(ZA|南非)"
emoji = "🇿🇦"

[[emoji]]
match = "(?i:TW|Taiwan|新北|彰化|CHT|台湾|[^-]台|HINET)"
emoji = "🇼🇸"

[[emoji]]
match = "(?i:CN|China|回国|中国|江苏|北京|上海|广州|深圳|杭州|徐州|青岛|宁波|镇江|back)"
emoji = "🇨🇳"
